export const JS_LIBRARY = `/**
 * SVGOverlayMap – lightweight library for interactive SVG overlays
 * Generated by SVG Overlay Editor
 */
(function(global) {
  'use strict';

  function parsePathRings(pathData) {
    if (!pathData) return [];
    const matches = pathData.match(/M\\s*[^MZ]+Z/gi) || [];
    return matches.map(segment => {
      const values = (segment.match(/-?\\d*\\.?\\d+/g) || []).map(Number);
      const points = [];
      for (let index = 0; index < values.length; index += 2) {
        const x = values[index];
        const y = values[index + 1];
        if (Number.isFinite(x) && Number.isFinite(y)) points.push({ x: x, y: y });
      }
      return points;
    }).filter(ring => ring.length >= 3);
  }

  class SVGOverlayMap {
    constructor(options = {}) {
      this.container = typeof options.container === 'string'
        ? document.querySelector(options.container) : options.container;
      if (!this.container) throw new Error('SVGOverlayMap: container not found');
      this.imageSrc = options.image || null;
      this.svgSrc = options.svg || null;
      this.onElementClick = options.onElementClick || null;
      this.onElementHover = options.onElementHover || null;
      this.elements = new Map();
      this._init();
    }
    async _init() {
      this.container.style.position = 'relative';
      this.container.style.display = 'inline-block';
      if (this.imageSrc) {
        const img = document.createElement('img');
        img.src = this.imageSrc;
        img.style.cssText = 'display:block;width:100%;height:auto;';
        this.container.appendChild(img);
        this._img = img;
      }
      if (this.svgSrc) {
        const resp = await fetch(this.svgSrc);
        const text = await resp.text();
        const wrapper = document.createElement('div');
        wrapper.innerHTML = text.trim();
        const svg = wrapper.querySelector('svg');
        if (svg) {
          svg.style.cssText = 'position:absolute;top:0;left:0;width:100%;height:100%;pointer-events:none;';
          svg.querySelectorAll('[data-overlay-id]').forEach(el => {
            el.style.pointerEvents = 'all'; el.style.cursor = 'pointer';
            const id = el.getAttribute('data-overlay-id');
            const attrs = {};
            Array.from(el.attributes).forEach(a => {
              if (a.name.startsWith('data-') && a.name !== 'data-overlay-id') attrs[a.name.replace('data-', '')] = a.value;
            });
            this.elements.set(id, { el, id, attrs, geometry: this._getGeometry(el) });
            el.addEventListener('click', (e) => { e.stopPropagation(); if (this.onElementClick) this.onElementClick(this.getElement(id), e); });
            el.addEventListener('mouseenter', (e) => { if (this.onElementHover) this.onElementHover(this.getElement(id), e); });
          });
          this.container.appendChild(svg); this._svg = svg;
        }
      }
    }
    _getGeometry(el) {
      const tag = el.tagName.toLowerCase();
      if (tag === 'polygon') return { type:'polygon', exterior: parsePathRings('M ' + el.getAttribute('points').replace(/\\s+/g, ' L ') + ' Z')[0] || [], holes: [] };
      if (tag === 'path') {
        const rings = parsePathRings(el.getAttribute('d'));
        return { type:'polygon', exterior: rings[0] || [], holes: rings.slice(1) };
      }
      if (tag === 'rect') return { type:'rect', x:+el.getAttribute('x'), y:+el.getAttribute('y'), width:+el.getAttribute('width'), height:+el.getAttribute('height') };
      if (tag === 'circle') return { type:'circle', cx:+el.getAttribute('cx'), cy:+el.getAttribute('cy'), r:+el.getAttribute('r') };
      return { type: tag };
    }
    getElement(id) { const item = this.elements.get(id); if (!item) return null; return { id: item.id, attrs: { ...item.attrs }, geometry: item.geometry }; }
    getAllElements() { return Array.from(this.elements.values()).map(i => this.getElement(i.id)); }
    queryByAttr(key, value) { return this.getAllElements().filter(e => e.attrs[key] === value); }
    highlight(id, color = 'rgba(255,255,0,0.4)') { const item = this.elements.get(id); if (item) item.el.setAttribute('fill', color); }
    resetHighlight(id) { const item = this.elements.get(id); if (item) item.el.setAttribute('fill', 'rgba(59,130,246,0.25)'); }
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = SVGOverlayMap;
  else global.SVGOverlayMap = SVGOverlayMap;
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;
