import { useState, useRef, useCallback, useEffect } from "react";

const FONT_LINK = "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&family=DM+Sans:wght@400;500;600;700&display=swap";

const JS_LIBRARY = `/**
 * SVGOverlayMap – lightweight library for interactive SVG overlays
 * Generated by SVG Overlay Editor
 */
(function(global) {
  'use strict';
  class SVGOverlayMap {
    constructor(options = {}) {
      this.container = typeof options.container === 'string'
        ? document.querySelector(options.container) : options.container;
      if (!this.container) throw new Error('SVGOverlayMap: container not found');
      this.imageSrc = options.image || null;
      this.svgSrc = options.svg || null;
      this.onElementClick = options.onElementClick || null;
      this.onElementHover = options.onElementHover || null;
      this.elements = new Map();
      this._init();
    }
    async _init() {
      this.container.style.position = 'relative';
      this.container.style.display = 'inline-block';
      if (this.imageSrc) {
        const img = document.createElement('img');
        img.src = this.imageSrc;
        img.style.cssText = 'display:block;width:100%;height:auto;';
        this.container.appendChild(img);
        this._img = img;
      }
      if (this.svgSrc) {
        const resp = await fetch(this.svgSrc);
        const text = await resp.text();
        const wrapper = document.createElement('div');
        wrapper.innerHTML = text.trim();
        const svg = wrapper.querySelector('svg');
        if (svg) {
          svg.style.cssText = 'position:absolute;top:0;left:0;width:100%;height:100%;pointer-events:none;';
          svg.querySelectorAll('[data-overlay-id]').forEach(el => {
            el.style.pointerEvents = 'all'; el.style.cursor = 'pointer';
            const id = el.getAttribute('data-overlay-id');
            const attrs = {};
            Array.from(el.attributes).forEach(a => {
              if (a.name.startsWith('data-') && a.name !== 'data-overlay-id') attrs[a.name.replace('data-', '')] = a.value;
            });
            this.elements.set(id, { el, id, attrs, geometry: this._getGeometry(el) });
            el.addEventListener('click', (e) => { e.stopPropagation(); if (this.onElementClick) this.onElementClick(this.getElement(id), e); });
            el.addEventListener('mouseenter', (e) => { if (this.onElementHover) this.onElementHover(this.getElement(id), e); });
          });
          this.container.appendChild(svg); this._svg = svg;
        }
      }
    }
    _getGeometry(el) {
      const tag = el.tagName.toLowerCase();
      if (tag === 'polygon') return { type:'polygon', points: el.getAttribute('points') };
      if (tag === 'rect') return { type:'rect', x:+el.getAttribute('x'), y:+el.getAttribute('y'), width:+el.getAttribute('width'), height:+el.getAttribute('height') };
      if (tag === 'circle') return { type:'circle', cx:+el.getAttribute('cx'), cy:+el.getAttribute('cy'), r:+el.getAttribute('r') };
      return { type: tag };
    }
    getElement(id) { const item = this.elements.get(id); if (!item) return null; return { id: item.id, attrs: { ...item.attrs }, geometry: item.geometry }; }
    getAllElements() { return Array.from(this.elements.values()).map(i => this.getElement(i.id)); }
    queryByAttr(key, value) { return this.getAllElements().filter(e => e.attrs[key] === value); }
    highlight(id, color = 'rgba(255,255,0,0.4)') { const item = this.elements.get(id); if (item) item.el.setAttribute('fill', color); }
    resetHighlight(id) { const item = this.elements.get(id); if (item) item.el.setAttribute('fill', 'rgba(59,130,246,0.25)'); }
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = SVGOverlayMap;
  else global.SVGOverlayMap = SVGOverlayMap;
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;

const styles = `
  @import url('${FONT_LINK}');
  * { margin:0; padding:0; box-sizing:border-box; }
  :root {
    --bg-primary: #0a0e17;
    --bg-secondary: #111827;
    --bg-tertiary: #1a2235;
    --bg-hover: #243049;
    --border: #2a3654;
    --border-active: #3b82f6;
    --text-primary: #e2e8f0;
    --text-secondary: #94a3b8;
    --text-muted: #64748b;
    --accent: #3b82f6;
    --accent-glow: rgba(59,130,246,0.3);
    --danger: #ef4444;
    --success: #10b981;
    --warning: #f59e0b;
    --polygon-fill: rgba(59,130,246,0.2);
    --polygon-stroke: #3b82f6;
    --polygon-active-fill: rgba(250,204,21,0.25);
    --polygon-active-stroke: #facc15;
    --polygon-selected-fill: rgba(16,185,129,0.2);
    --polygon-selected-stroke: #10b981;
    --group-purple: #a78bfa;
    --group-purple-bg: rgba(167,139,250,0.1);
    --vertex-edit: #f97316;
  }
  body { font-family:'DM Sans',sans-serif; background:var(--bg-primary); color:var(--text-primary); overflow:hidden; height:100vh; }
  .app { display:flex; flex-direction:column; height:100vh; }

  .topbar {
    display:flex; align-items:center; justify-content:space-between;
    padding:0 20px; height:56px; min-height:56px;
    background:var(--bg-secondary); border-bottom:1px solid var(--border); z-index:100;
  }
  .topbar-brand { display:flex; align-items:center; gap:10px; font-family:'JetBrains Mono',monospace; font-weight:700; font-size:15px; letter-spacing:-0.5px; }
  .topbar-brand svg { flex-shrink:0; }
  .topbar-tabs { display:flex; gap:2px; background:var(--bg-primary); border-radius:8px; padding:3px; }
  .topbar-tab {
    padding:6px 20px; border-radius:6px; border:none; cursor:pointer;
    font-family:'DM Sans',sans-serif; font-size:13px; font-weight:600;
    background:transparent; color:var(--text-muted); transition:all 0.2s;
  }
  .topbar-tab:hover { color:var(--text-secondary); }
  .topbar-tab.active { background:var(--accent); color:white; }

  .btn {
    padding:7px 16px; border-radius:6px; border:1px solid var(--border);
    font-family:'DM Sans',sans-serif; font-size:12px; font-weight:600;
    cursor:pointer; transition:all 0.15s; display:inline-flex; align-items:center; gap:6px;
    background:var(--bg-tertiary); color:var(--text-primary);
  }
  .btn:hover { border-color:var(--text-muted); background:var(--bg-hover); }
  .btn-primary { background:var(--accent); border-color:var(--accent); color:white; }
  .btn-primary:hover { background:#2563eb; }
  .btn-danger { border-color:var(--danger); color:var(--danger); }
  .btn-danger:hover { background:rgba(239,68,68,0.1); }
  .btn-sm { padding:4px 10px; font-size:11px; }
  .btn-xs { padding:2px 6px; font-size:10px; }
  .btn-purple { background:rgba(167,139,250,0.15); border-color:var(--group-purple); color:var(--group-purple); }
  .btn-purple:hover { background:rgba(167,139,250,0.25); }
  .btn-orange { border-color:var(--vertex-edit); color:var(--vertex-edit); }
  .btn-orange:hover { background:rgba(249,115,22,0.1); }

  .workspace { display:flex; flex:1; overflow:hidden; }
  .canvas-area {
    flex:1; display:flex; align-items:center; justify-content:center;
    background:var(--bg-primary); position:relative; overflow:hidden;
    background-image:radial-gradient(circle at 1px 1px, rgba(255,255,255,0.03) 1px, transparent 0);
    background-size:24px 24px;
  }
  .sidebar {
    width:360px; min-width:360px; background:var(--bg-secondary);
    border-left:1px solid var(--border); display:flex; flex-direction:column; overflow:hidden;
  }
  .sidebar-tabs { display:flex; border-bottom:1px solid var(--border); }
  .sidebar-tab {
    flex:1; padding:10px 12px; border:none; cursor:pointer;
    font-family:'JetBrains Mono',monospace; font-size:11px; font-weight:600;
    text-transform:uppercase; letter-spacing:0.5px;
    background:transparent; color:var(--text-muted); transition:all 0.15s;
    border-bottom:2px solid transparent;
  }
  .sidebar-tab:hover { color:var(--text-secondary); }
  .sidebar-tab.active { color:var(--accent); border-bottom-color:var(--accent); }
  .sidebar-content { flex:1; overflow-y:auto; padding:16px 20px; }

  /* Fixed action bar at bottom of sidebar */
  .sidebar-actions {
    padding:12px 20px; border-top:1px solid var(--border);
    background:var(--bg-secondary); display:flex; flex-direction:column; gap:6px;
    flex-shrink:0;
  }
  .sidebar-actions .btn { width:100%; justify-content:center; }

  .canvas-wrapper { position:relative; display:inline-block; box-shadow:0 0 60px rgba(0,0,0,0.5); }
  .canvas-wrapper img { display:block; user-select:none; -webkit-user-drag:none; }
  .canvas-wrapper svg { position:absolute; top:0; left:0; width:100%; height:100%; }
  .drawing-svg { cursor:crosshair; }
  .drawing-svg polygon { cursor:pointer; transition:fill 0.15s; }
  .drawing-svg polygon:hover { fill:rgba(59,130,246,0.35) !important; }

  .upload-zone {
    border:2px dashed var(--border); border-radius:12px;
    padding:60px 40px; text-align:center; cursor:pointer; transition:all 0.2s; max-width:480px;
  }
  .upload-zone:hover { border-color:var(--accent); background:rgba(59,130,246,0.05); }
  .upload-zone h3 { font-size:16px; margin-bottom:8px; }
  .upload-zone p { font-size:13px; color:var(--text-muted); }

  .mode-selector { display:flex; flex-direction:column; align-items:center; gap:24px; max-width:600px; }
  .mode-selector h2 { font-family:'JetBrains Mono',monospace; font-size:18px; font-weight:700; }
  .mode-selector > p { font-size:13px; color:var(--text-muted); margin-top:-16px; }
  .mode-cards { display:flex; gap:20px; }
  .mode-card {
    width:260px; padding:32px 24px; border-radius:12px; border:1px solid var(--border);
    background:var(--bg-secondary); cursor:pointer; transition:all 0.2s; text-align:center;
  }
  .mode-card:hover { border-color:var(--accent); background:var(--bg-tertiary); transform:translateY(-2px); box-shadow:0 8px 30px rgba(0,0,0,0.3); }
  .mode-card svg { margin-bottom:16px; }
  .mode-card h3 { font-size:15px; font-weight:700; margin-bottom:6px; }
  .mode-card p { font-size:12px; color:var(--text-muted); line-height:1.5; }

  .edit-upload-step { display:flex; flex-direction:column; align-items:center; gap:20px; max-width:600px; }
  .edit-upload-step h3 { font-family:'JetBrains Mono',monospace; font-size:15px; margin-bottom:4px; }
  .edit-upload-row { display:flex; gap:20px; }
  .upload-zone-mini {
    border:2px dashed var(--border); border-radius:12px;
    padding:32px 28px; text-align:center; cursor:pointer; transition:all 0.2s; width:240px;
  }
  .upload-zone-mini:hover { border-color:var(--accent); background:rgba(59,130,246,0.05); }
  .upload-zone-mini h4 { font-size:13px; margin-bottom:4px; }
  .upload-zone-mini p { font-size:11px; color:var(--text-muted); }

  .form-group { margin-bottom:14px; }
  .form-label {
    display:block; font-size:11px; font-weight:600; margin-bottom:5px;
    color:var(--text-muted); text-transform:uppercase; letter-spacing:0.5px;
    font-family:'JetBrains Mono',monospace;
  }
  .form-input {
    width:100%; padding:8px 12px; border-radius:6px;
    border:1px solid var(--border); background:var(--bg-primary);
    color:var(--text-primary); font-size:13px; font-family:'DM Sans',sans-serif;
    transition:border-color 0.15s; outline:none;
  }
  .form-input:focus { border-color:var(--accent); box-shadow:0 0 0 2px var(--accent-glow); }
  .form-input::placeholder { color:var(--text-muted); }

  .attr-row { display:flex; gap:6px; align-items:center; margin-bottom:8px; animation:fadeIn 0.15s ease; }
  .attr-row .form-input { flex:1; }
  .remove-attr {
    width:28px; height:28px; border-radius:4px; border:none; cursor:pointer;
    background:transparent; color:var(--danger); font-size:16px;
    display:flex; align-items:center; justify-content:center;
    transition:background 0.15s; flex-shrink:0;
  }
  .remove-attr:hover { background:rgba(239,68,68,0.1); }

  .element-item {
    padding:8px 12px; border-radius:8px; margin-bottom:4px;
    border:1px solid var(--border); cursor:pointer; transition:all 0.15s;
    display:flex; align-items:center; gap:8px;
  }
  .element-item:hover { border-color:var(--text-muted); background:var(--bg-tertiary); }
  .element-item.selected { border-color:var(--success); background:rgba(16,185,129,0.06); }
  .element-item .el-info { flex:1; min-width:0; }
  .element-item .el-id {
    font-family:'JetBrains Mono',monospace; font-size:12px; font-weight:500;
    white-space:nowrap; overflow:hidden; text-overflow:ellipsis;
  }
  .element-item .el-points { font-size:10px; color:var(--text-muted); }
  .element-item .el-actions { display:flex; gap:3px; flex-shrink:0; }
  .inline-rename {
    font-family:'JetBrains Mono',monospace; font-size:12px; font-weight:500;
    background:var(--bg-primary); border:1px solid var(--accent); border-radius:4px;
    color:var(--text-primary); padding:2px 6px; outline:none; width:100%;
    box-shadow:0 0 0 2px var(--accent-glow);
  }

  .group-card {
    padding:12px; border-radius:8px; margin-bottom:8px;
    border:1px solid var(--border); transition:all 0.15s;
  }
  .group-card.active-group { border-color:var(--group-purple); background:var(--group-purple-bg); }
  .group-card .group-name {
    font-family:'JetBrains Mono',monospace; font-size:13px; font-weight:600;
    margin-bottom:4px; display:flex; align-items:center; justify-content:space-between;
  }
  .group-card .group-attrs { font-size:11px; color:var(--text-muted); line-height:1.6; }
  .group-card .group-actions { display:flex; gap:4px; margin-top:8px; }

  .group-switcher { position:relative; margin-bottom:14px; }
  .group-switcher-btn {
    width:100%; padding:8px 12px; border-radius:6px; border:1px solid var(--border);
    background:var(--bg-primary); color:var(--text-primary); font-size:12px;
    font-family:'DM Sans',sans-serif; cursor:pointer; transition:all 0.15s;
    display:flex; align-items:center; justify-content:space-between;
  }
  .group-switcher-btn:hover { border-color:var(--text-muted); }
  .group-switcher-btn.has-group { border-color:var(--group-purple); background:var(--group-purple-bg); }
  .group-switcher-btn .gs-label { display:flex; align-items:center; gap:8px; }
  .group-switcher-btn .gs-dot { width:8px; height:8px; border-radius:50%; background:var(--group-purple); flex-shrink:0; }
  .group-switcher-btn .gs-name { font-family:'JetBrains Mono',monospace; font-weight:600; color:var(--group-purple); }
  .group-switcher-btn .gs-placeholder { color:var(--text-muted); }
  .group-switcher-btn .gs-arrow { color:var(--text-muted); font-size:10px; transition:transform 0.15s; }
  .group-switcher-btn .gs-arrow.open { transform:rotate(180deg); }

  .group-dropdown {
    position:absolute; top:calc(100% + 4px); left:0; right:0; z-index:50;
    background:var(--bg-secondary); border:1px solid var(--border); border-radius:8px;
    box-shadow:0 12px 40px rgba(0,0,0,0.5); max-height:220px; overflow-y:auto;
    animation:fadeIn 0.12s ease;
  }
  .group-dropdown-item {
    padding:10px 14px; cursor:pointer; transition:all 0.1s;
    display:flex; align-items:center; justify-content:space-between;
    border-bottom:1px solid var(--border); font-size:12px;
  }
  .group-dropdown-item:last-child { border-bottom:none; }
  .group-dropdown-item:hover { background:var(--bg-hover); }
  .group-dropdown-item.active-item { background:var(--group-purple-bg); }
  .group-dropdown-item .gdi-name { font-family:'JetBrains Mono',monospace; font-weight:600; }
  .group-dropdown-item .gdi-attrs { font-size:10px; color:var(--text-muted); margin-top:2px; }
  .group-dropdown-item .gdi-check { color:var(--group-purple); font-weight:700; }
  .group-dropdown-none {
    padding:10px 14px; cursor:pointer; transition:all 0.1s;
    color:var(--text-muted); font-size:12px; border-bottom:1px solid var(--border);
  }
  .group-dropdown-none:hover { background:var(--bg-hover); }

  .statusbar {
    height:32px; min-height:32px; display:flex; align-items:center;
    padding:0 20px; background:var(--bg-secondary);
    border-top:1px solid var(--border);
    font-family:'JetBrains Mono',monospace; font-size:11px; color:var(--text-muted); gap:20px;
  }
  .status-dot { width:6px; height:6px; border-radius:50%; display:inline-block; margin-right:6px; }
  .status-dot.green { background:var(--success); }
  .status-dot.yellow { background:var(--warning); }
  .status-dot.blue { background:var(--accent); }
  .status-dot.orange { background:var(--vertex-edit); }

  .badge {
    display:inline-flex; align-items:center; padding:2px 8px;
    border-radius:4px; font-size:10px; font-weight:600;
    font-family:'JetBrains Mono',monospace;
  }
  .badge-blue { background:rgba(59,130,246,0.15); color:var(--accent); }
  .badge-green { background:rgba(16,185,129,0.15); color:var(--success); }
  .badge-purple { background:rgba(167,139,250,0.15); color:var(--group-purple); }
  .badge-orange { background:rgba(249,115,22,0.15); color:var(--vertex-edit); }

  .divider { height:1px; background:var(--border); margin:16px 0; }
  .hint-box {
    padding:12px; border-radius:8px; background:rgba(59,130,246,0.06);
    border:1px solid rgba(59,130,246,0.15); font-size:12px; color:var(--text-secondary); line-height:1.6;
  }

  .validator-attrs-table { width:100%; font-size:12px; border-collapse:collapse; }
  .validator-attrs-table td { padding:6px 10px; border-bottom:1px solid var(--border); }
  .validator-attrs-table td:first-child { font-family:'JetBrains Mono',monospace; font-weight:600; color:var(--accent); width:40%; }

  .zoom-controls {
    position:absolute; bottom:16px; right:16px; display:flex; gap:4px; z-index:10;
  }
  .zoom-btn {
    width:36px; height:36px; border-radius:8px; border:1px solid var(--border);
    background:var(--bg-secondary); color:var(--text-primary);
    font-size:18px; cursor:pointer; display:flex; align-items:center; justify-content:center;
    transition:all 0.15s;
  }
  .zoom-btn:hover { background:var(--bg-hover); border-color:var(--text-muted); }
  .zoom-info {
    height:36px; padding:0 12px; border-radius:8px; border:1px solid var(--border);
    background:var(--bg-secondary); color:var(--text-muted);
    font-family:'JetBrains Mono',monospace; font-size:11px; display:flex; align-items:center;
  }

  .geom-hint {
    padding:8px 12px; border-radius:6px; background:rgba(249,115,22,0.08);
    border:1px solid rgba(249,115,22,0.2); font-size:11px; color:var(--vertex-edit);
    margin-bottom:12px; line-height:1.5;
  }

  @keyframes fadeIn { from { opacity:0; transform:translateY(-4px); } to { opacity:1; transform:translateY(0); } }
  @keyframes pulse-ring { 0% { transform:scale(1); opacity:0.5; } 100% { transform:scale(1.6); opacity:0; } }
  ::-webkit-scrollbar { width:6px; }
  ::-webkit-scrollbar-track { background:transparent; }
  ::-webkit-scrollbar-thumb { background:var(--border); border-radius:3px; }
  ::-webkit-scrollbar-thumb:hover { background:var(--text-muted); }
`;

function Logo() {
  return (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <rect x="2" y="2" width="24" height="24" rx="6" stroke="#3b82f6" strokeWidth="2" fill="rgba(59,130,246,0.1)"/>
      <polygon points="8,18 11,10 17,8 20,14 16,20" fill="rgba(59,130,246,0.3)" stroke="#3b82f6" strokeWidth="1.5" strokeLinejoin="round"/>
      <circle cx="11" cy="10" r="1.5" fill="#3b82f6"/><circle cx="17" cy="8" r="1.5" fill="#3b82f6"/>
      <circle cx="20" cy="14" r="1.5" fill="#3b82f6"/><circle cx="16" cy="20" r="1.5" fill="#3b82f6"/>
      <circle cx="8" cy="18" r="1.5" fill="#3b82f6"/>
    </svg>
  );
}

function generateSVG(elements, imgWidth, imgHeight) {
  let polys = '';
  elements.forEach(el => {
    const pts = el.points.map(p => `${p.x},${p.y}`).join(' ');
    let attrs = ` data-overlay-id="${el.id}"`;
    if (el.groupName) attrs += ` data-group="${el.groupName}"`;
    el.attributes.forEach(a => {
      if (a.key && a.key !== 'id') attrs += ` data-${a.key.toLowerCase().replace(/\s+/g,'-')}="${a.value}"`;
    });
    polys += `  <polygon points="${pts}"${attrs} fill="rgba(59,130,246,0.25)" stroke="#3b82f6" stroke-width="2" stroke-linejoin="round" />\n`;
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${imgWidth} ${imgHeight}" width="${imgWidth}" height="${imgHeight}">\n${polys}</svg>`;
}

function parseSVGFile(svgText) {
  const parser = new DOMParser();
  const doc = parser.parseFromString(svgText, 'image/svg+xml');
  const polys = doc.querySelectorAll('[data-overlay-id]');
  return Array.from(polys).map(p => {
    const attrs = [];
    const groupName = p.getAttribute('data-group') || null;
    Array.from(p.attributes).forEach(a => {
      if (a.name.startsWith('data-') && a.name !== 'data-overlay-id' && a.name !== 'data-group')
        attrs.push({ key: a.name.replace('data-', ''), value: a.value });
    });
    const pointsStr = p.getAttribute('points') || '';
    const points = pointsStr.split(/\s+/).filter(Boolean).map(pair => {
      const [x, y] = pair.split(',').map(Number);
      return { x, y };
    });
    return { id: p.getAttribute('data-overlay-id'), points, attributes: attrs, groupName };
  });
}

// ─── Zoom/Pan Hook (single atomic state) ───
function useZoomPan(canvasRef, disabled = false) {
  const [view, setView] = useState({ zoom: 1, panX: 0, panY: 0 });
  const isPanning = useRef(false);
  const panStart = useRef({ x: 0, y: 0 });
  const panStartView = useRef({ panX: 0, panY: 0 });
  const disabledRef = useRef(disabled);
  disabledRef.current = disabled;

  const handleWheel = useCallback((e) => {
    e.preventDefault();
    if (disabledRef.current) return;
    const el = canvasRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    const mx = e.clientX - rect.left;
    const my = e.clientY - rect.top;
    const factor = e.deltaY > 0 ? 0.9 : 1.1;
    setView(prev => {
      const newZoom = Math.min(10, Math.max(0.1, prev.zoom * factor));
      const scale = newZoom / prev.zoom;
      return {
        zoom: newZoom,
        panX: mx - scale * (mx - prev.panX),
        panY: my - scale * (my - prev.panY),
      };
    });
  }, [canvasRef]);

  const handleMouseDown = useCallback((e) => {
    if (disabledRef.current) return;
    if (e.button === 1 || (e.button === 0 && e.ctrlKey)) {
      e.preventDefault(); isPanning.current = true;
      panStart.current = { x: e.clientX, y: e.clientY };
      setView(prev => { panStartView.current = { panX: prev.panX, panY: prev.panY }; return prev; });
      if (canvasRef.current) canvasRef.current.style.cursor = 'grabbing';
    }
  }, [canvasRef]);

  const handleMouseMove = useCallback((e) => {
    if (!isPanning.current) return;
    const dx = e.clientX - panStart.current.x;
    const dy = e.clientY - panStart.current.y;
    setView(prev => ({ ...prev, panX: panStartView.current.panX + dx, panY: panStartView.current.panY + dy }));
  }, []);

  const handleMouseUp = useCallback(() => {
    isPanning.current = false;
    if (canvasRef.current) canvasRef.current.style.cursor = '';
  }, [canvasRef]);

  useEffect(() => {
    const el = canvasRef.current; if (!el) return;
    el.addEventListener('wheel', handleWheel, { passive: false });
    el.addEventListener('mousedown', handleMouseDown);
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
    return () => {
      el.removeEventListener('wheel', handleWheel); el.removeEventListener('mousedown', handleMouseDown);
      window.removeEventListener('mousemove', handleMouseMove); window.removeEventListener('mouseup', handleMouseUp);
    };
  }, [canvasRef, handleWheel, handleMouseDown, handleMouseMove, handleMouseUp]);

  const centerOn = useCallback((contentW, contentH) => {
    const el = canvasRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    setView({ zoom: 1, panX: (rect.width - contentW) / 2, panY: (rect.height - contentH) / 2 });
  }, [canvasRef]);

  const resetView = useCallback((contentW, contentH) => { centerOn(contentW, contentH); }, [centerOn]);

  const zoomIn = useCallback(() => {
    const el = canvasRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    const cx = rect.width / 2, cy = rect.height / 2;
    setView(prev => {
      const newZ = Math.min(10, prev.zoom * 1.3);
      const s = newZ / prev.zoom;
      return { zoom: newZ, panX: cx - s * (cx - prev.panX), panY: cy - s * (cy - prev.panY) };
    });
  }, [canvasRef]);

  const zoomOut = useCallback(() => {
    const el = canvasRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    const cx = rect.width / 2, cy = rect.height / 2;
    setView(prev => {
      const newZ = Math.max(0.1, prev.zoom / 1.3);
      const s = newZ / prev.zoom;
      return { zoom: newZ, panX: cx - s * (cx - prev.panX), panY: cy - s * (cy - prev.panY) };
    });
  }, [canvasRef]);

  // Expose as flat values for compatibility
  const zoom = view.zoom;
  const pan = { x: view.panX, y: view.panY };
  return { zoom, pan, resetView, centerOn, zoomIn, zoomOut, isPanning };
}

// ─── Group Dropdown Switcher ───
function GroupSwitcher({ groups, activeGroupId, setActiveGroupId }) {
  const [open, setOpen] = useState(false);
  const ref = useRef(null);
  const activeGroup = groups.find(g => g.id === activeGroupId) || null;
  useEffect(() => {
    const handler = (e) => { if (ref.current && !ref.current.contains(e.target)) setOpen(false); };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);
  if (groups.length === 0) return null;
  return (
    <div className="group-switcher" ref={ref}>
      <button className={`group-switcher-btn ${activeGroup ? 'has-group' : ''}`} onClick={() => setOpen(!open)}>
        <div className="gs-label">
          {activeGroup ? <><div className="gs-dot" /><span className="gs-name">{activeGroup.name}</span></> : <span className="gs-placeholder">Žádná aktivní skupina</span>}
        </div>
        <span className={`gs-arrow ${open ? 'open' : ''}`}>▼</span>
      </button>
      {open && (
        <div className="group-dropdown">
          <div className="group-dropdown-none" onClick={() => { setActiveGroupId(null); setOpen(false); }}>— Bez skupiny —</div>
          {groups.map(g => (
            <div key={g.id} className={`group-dropdown-item ${activeGroupId === g.id ? 'active-item' : ''}`}
              onClick={() => { setActiveGroupId(g.id); setOpen(false); }}>
              <div><div className="gdi-name">{g.name}</div><div className="gdi-attrs">{g.attrKeys.join(', ')}</div></div>
              {activeGroupId === g.id && <span className="gdi-check">✓</span>}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ═══════════════════════════════════════════
// ─── MAIN APP ───
// ═══════════════════════════════════════════
export default function App() {
  const [mode, setMode] = useState('editor');
  return (
    <><style>{styles}</style>
      <div className="app">
        <div className="topbar">
          <div className="topbar-brand"><Logo /><span>SVG Overlay Editor</span></div>
          <div className="topbar-tabs">
            <button className={`topbar-tab ${mode==='editor'?'active':''}`} onClick={()=>setMode('editor')}>Editor</button>
            <button className={`topbar-tab ${mode==='validator'?'active':''}`} onClick={()=>setMode('validator')}>Validátor</button>
          </div>
          <div style={{width:160}}/>
        </div>
        <div style={{ display: mode === 'editor' ? 'contents' : 'none' }}><Editor /></div>
        <div style={{ display: mode === 'validator' ? 'contents' : 'none' }}><Validator /></div>
      </div>
    </>
  );
}

// ═══════════════════════════════════════════
// ─── EDITOR ───
// ═══════════════════════════════════════════
function Editor() {
  const [phase, setPhase] = useState('choose');
  const [image, setImage] = useState(null);
  const [imgSize, setImgSize] = useState({ w: 0, h: 0 });
  const [elements, setElements] = useState([]);
  const [currentPoints, setCurrentPoints] = useState([]);
  const [isDrawing, setIsDrawing] = useState(false);
  const [selectedId, setSelectedId] = useState(null);
  const [editId, setEditId] = useState(null);       // editing attributes
  const [editAttrs, setEditAttrs] = useState([{ key: '', value: '' }]);
  const [editElId, setEditElId] = useState('');
  const [sidebarTab, setSidebarTab] = useState('elements');
  const [renamingId, setRenamingId] = useState(null);
  const [renameValue, setRenameValue] = useState('');
  // Geometry editing
  const [editGeomId, setEditGeomId] = useState(null);
  const [draggingVertex, setDraggingVertex] = useState(null); // { elId, pointIdx }

  // Groups
  const [groups, setGroups] = useState([]);
  const [activeGroupId, setActiveGroupId] = useState(null);
  const [editingGroup, setEditingGroup] = useState(null);
  const [groupForm, setGroupForm] = useState({ name: '', attrKeys: [''] });
  const [editModeSvgLoaded, setEditModeSvgLoaded] = useState(false);

  const svgRef = useRef(null);
  const imgRef = useRef(null);
  const fileRef = useRef(null);
  const editImgRef = useRef(null);
  const editSvgRef = useRef(null);
  const canvasAreaRef = useRef(null);
  const renameInputRef = useRef(null);
  const { zoom, pan, resetView, centerOn, zoomIn, zoomOut, isPanning } = useZoomPan(canvasAreaRef, phase !== 'canvas');

  const activeGroup = groups.find(g => g.id === activeGroupId) || null;

  // Compute displayed image size (respects max-width: 70vw, max-height: 75vh)
  const getDisplayedImgSize = useCallback(() => {
    if (!imgSize.w || !imgSize.h) return { w: 0, h: 0 };
    const maxW = window.innerWidth * 0.7;
    const maxH = window.innerHeight * 0.75;
    const scale = Math.min(maxW / imgSize.w, maxH / imgSize.h, 1);
    return { w: imgSize.w * scale, h: imgSize.h * scale };
  }, [imgSize]);

  // Center image when entering canvas phase
  useEffect(() => {
    if (phase === 'canvas' && imgSize.w > 0) {
      const ds = getDisplayedImgSize();
      // Small delay to ensure canvas-area is rendered
      requestAnimationFrame(() => centerOn(ds.w, ds.h));
    }
  }, [phase, imgSize, centerOn, getDisplayedImgSize]);

  // ── Image uploads ──
  const handleImageUpload = (file) => {
    if (!file || !file.type.startsWith('image/')) return;
    const url = URL.createObjectURL(file);
    const img = new Image();
    img.onload = () => {
      setImgSize({ w: img.naturalWidth, h: img.naturalHeight });
      setImage(url); setElements([]); setCurrentPoints([]); setIsDrawing(false);
      setSelectedId(null); setEditId(null); setEditGeomId(null); setPhase('canvas');
    };
    img.src = url;
  };
  const handleEditImageUpload = (file) => {
    if (!file || !file.type.startsWith('image/')) return;
    const url = URL.createObjectURL(file);
    const img = new Image();
    img.onload = () => { setImgSize({ w: img.naturalWidth, h: img.naturalHeight }); setImage(url); };
    img.src = url;
  };
  const handleEditSvgUpload = (file) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (e) => {
      const parsed = parseSVGFile(e.target.result);
      setElements(parsed); setEditModeSvgLoaded(true);
      const groupNames = [...new Set(parsed.map(p => p.groupName).filter(Boolean))];
      if (groupNames.length > 0 && groups.length === 0) {
        setGroups(groupNames.map(name => {
          const sample = parsed.find(p => p.groupName === name);
          return { id: `grp_${Date.now()}_${name}`, name, attrKeys: sample ? sample.attributes.map(a => a.key) : [] };
        }));
      }
    };
    reader.readAsText(file);
  };
  const startEditCanvas = () => {
    if (image && editModeSvgLoaded) { setPhase('canvas'); setCurrentPoints([]); setIsDrawing(false); setSelectedId(null); }
  };
  const goBack = () => {
    setPhase('choose'); setImage(null); setElements([]); setCurrentPoints([]);
    setIsDrawing(false); setSelectedId(null); setEditId(null); setEditGeomId(null);
    setEditModeSvgLoaded(false);
  };

  // ── SVG point from mouse event ──
  const getSVGPoint = useCallback((e) => {
    if (!svgRef.current || !imgRef.current) return null;
    const rect = imgRef.current.getBoundingClientRect();
    return {
      x: Math.round((e.clientX - rect.left) * (imgSize.w / rect.width) * 100) / 100,
      y: Math.round((e.clientY - rect.top) * (imgSize.h / rect.height) * 100) / 100,
    };
  }, [imgSize]);

  // ── Canvas click: draw or select ──
  const handleCanvasClick = useCallback((e) => {
    if (isPanning.current || e.ctrlKey) return;
    // If in geometry edit mode, clicks on canvas don't create new polygons
    if (editGeomId) return;
    if (e.target.tagName === 'polygon' && !isDrawing) return;
    const pt = getSVGPoint(e);
    if (!pt) return;
    if (currentPoints.length >= 3) {
      const first = currentPoints[0];
      const dist = Math.sqrt((pt.x - first.x) ** 2 + (pt.y - first.y) ** 2);
      const rect = imgRef.current.getBoundingClientRect();
      if (dist < 25 * (imgSize.w / rect.width)) { finishPolygon(currentPoints); return; }
    }
    setCurrentPoints(prev => [...prev, pt]);
    setIsDrawing(true);
  }, [currentPoints, getSVGPoint, isDrawing, imgSize, editGeomId]);

  const handleDoubleClick = useCallback((e) => {
    e.preventDefault();
    if (currentPoints.length >= 3) finishPolygon(currentPoints);
  }, [currentPoints]);

  const finishPolygon = (points) => {
    const newId = `element_${Date.now()}`;
    const attrs = activeGroup ? activeGroup.attrKeys.map(k => ({ key: k, value: '' })) : [{ key: '', value: '' }];
    setElements(prev => [...prev, { id: newId, points: [...points], attributes: [], groupName: activeGroup ? activeGroup.name : null }]);
    setCurrentPoints([]); setIsDrawing(false);
    setSelectedId(newId);
    setEditId(newId); setEditElId(newId); setEditAttrs(attrs); setSidebarTab('elements');
  };

  const handlePolygonClick = (e, elId) => {
    e.stopPropagation();
    if (isDrawing) return;
    if (editGeomId && editGeomId !== elId) return;
    setSelectedId(elId);
  };

  // ── Attribute editing ──
  const startEditAttrs = (elId) => {
    const el = elements.find(x => x.id === elId);
    if (!el) return;
    setEditId(elId); setEditElId(el.id);
    setEditAttrs(el.attributes.length > 0 ? [...el.attributes] : [{ key: '', value: '' }]);
    setEditGeomId(null); setSidebarTab('elements');
  };
  const saveAttributes = () => {
    if (!editId) return;
    setElements(prev => prev.map(el => el.id === editId ? { ...el, id: editElId || el.id, attributes: editAttrs.filter(a => a.key.trim()) } : el));
    if (editElId && editElId !== editId) setSelectedId(editElId);
    setEditId(null);
  };
  const deleteElement = (elId) => {
    setElements(prev => prev.filter(e => e.id !== elId));
    if (selectedId === elId) setSelectedId(null);
    if (editId === elId) setEditId(null);
    if (editGeomId === elId) setEditGeomId(null);
  };

  // ── Inline rename ──
  const startRename = (elId) => {
    setRenamingId(elId);
    setRenameValue(elId);
    setTimeout(() => renameInputRef.current?.select(), 0);
  };
  const commitRename = () => {
    if (!renamingId) return;
    const newName = renameValue.trim() || renamingId;
    setElements(prev => prev.map(el => el.id === renamingId ? { ...el, id: newName } : el));
    if (selectedId === renamingId) setSelectedId(newName);
    if (editId === renamingId) { setEditId(newName); setEditElId(newName); }
    if (editGeomId === renamingId) setEditGeomId(newName);
    setRenamingId(null);
  };
  const cancelRename = () => setRenamingId(null);

  // ── Geometry editing ──
  const startGeomEdit = (elId) => {
    setEditGeomId(elId); setEditId(null); setSelectedId(elId); setSidebarTab('elements');
  };
  const stopGeomEdit = () => setEditGeomId(null);

  const handleVertexMouseDown = (e, elId, pointIdx) => {
    e.stopPropagation(); e.preventDefault();
    setDraggingVertex({ elId, pointIdx });
  };

  const handleVertexDrag = useCallback((e) => {
    if (!draggingVertex) return;
    const pt = getSVGPoint(e);
    if (!pt) return;
    setElements(prev => prev.map(el => {
      if (el.id !== draggingVertex.elId) return el;
      const newPts = [...el.points];
      newPts[draggingVertex.pointIdx] = pt;
      return { ...el, points: newPts };
    }));
  }, [draggingVertex, getSVGPoint]);

  const handleVertexMouseUp = useCallback(() => { setDraggingVertex(null); }, []);

  useEffect(() => {
    if (!draggingVertex) return;
    window.addEventListener('mousemove', handleVertexDrag);
    window.addEventListener('mouseup', handleVertexMouseUp);
    return () => { window.removeEventListener('mousemove', handleVertexDrag); window.removeEventListener('mouseup', handleVertexMouseUp); };
  }, [draggingVertex, handleVertexDrag, handleVertexMouseUp]);

  // Add vertex: click on edge midpoint
  const addVertex = (elId, afterIdx) => {
    setElements(prev => prev.map(el => {
      if (el.id !== elId) return el;
      const pts = [...el.points];
      const p1 = pts[afterIdx];
      const p2 = pts[(afterIdx + 1) % pts.length];
      const mid = { x: Math.round((p1.x + p2.x) / 2 * 100) / 100, y: Math.round((p1.y + p2.y) / 2 * 100) / 100 };
      pts.splice(afterIdx + 1, 0, mid);
      return { ...el, points: pts };
    }));
  };

  const removeVertex = (elId, idx) => {
    setElements(prev => prev.map(el => {
      if (el.id !== elId || el.points.length <= 3) return el;
      return { ...el, points: el.points.filter((_, i) => i !== idx) };
    }));
  };

  // ── Keyboard ──
  useEffect(() => {
    const handler = (e) => {
      if (e.key === 'Escape') {
        if (editGeomId) { stopGeomEdit(); return; }
        setCurrentPoints([]); setIsDrawing(false);
      }
      if (e.key === 'F2' && selectedId && !editId && !renamingId) {
        e.preventDefault(); startRename(selectedId);
      }
      if (e.key === 'Delete' && selectedId && !editId && !renamingId) {
        deleteElement(selectedId);
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [selectedId, editId, renamingId, editGeomId]);

  // ── Export ──
  const exportSVG = () => downloadFile(generateSVG(elements, imgSize.w, imgSize.h), 'overlay.svg', 'image/svg+xml');
  const exportLibrary = () => downloadFile(JS_LIBRARY, 'svg-overlay-map.js', 'text/javascript');
  const downloadFile = (content, name, type) => {
    const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url);
  };

  // ── Group management ──
  const startNewGroup = () => { setEditingGroup('new'); setGroupForm({ name: '', attrKeys: [''] }); };
  const startEditGroup = (g) => { setEditingGroup(g.id); setGroupForm({ name: g.name, attrKeys: [...g.attrKeys] }); };
  const saveGroup = () => {
    const name = groupForm.name.trim();
    const attrKeys = groupForm.attrKeys.filter(k => k.trim());
    if (!name || attrKeys.length === 0) return;
    if (editingGroup === 'new') {
      const ng = { id: `grp_${Date.now()}`, name, attrKeys };
      setGroups(prev => [...prev, ng]); setActiveGroupId(ng.id);
    } else {
      setGroups(prev => prev.map(g => g.id === editingGroup ? { ...g, name, attrKeys } : g));
    }
    setEditingGroup(null);
  };
  const deleteGroup = (gId) => { setGroups(prev => prev.filter(g => g.id !== gId)); if (activeGroupId === gId) setActiveGroupId(null); };

  // ── Zoom-compensated drawing sizes (constant screen appearance) ──
  // displayScale = how many SVG units per 1 CSS pixel (without zoom)
  const renderedW = imgRef.current ? imgRef.current.clientWidth : (imgSize.w || 1);
  const displayScale = imgSize.w / renderedW;
  // Target screen sizes in CSS pixels, converted to SVG units and zoom-compensated
  const dotRadius = (7 * displayScale) / zoom;
  const strokeW = (2.5 * displayScale) / zoom;
  const closeDotRadius = dotRadius * 1.5;
  const vertexR = (6 * displayScale) / zoom;
  const midpointR = vertexR * 0.6;

  const editGeomEl = editGeomId ? elements.find(e => e.id === editGeomId) : null;

  // ═══ RENDER ═══
  return (
    <>
      <div className="workspace">
        <div className="canvas-area" ref={canvasAreaRef}
          style={phase === 'canvas' ? { alignItems: 'flex-start', justifyContent: 'flex-start' } : {}}>

          {/* ── Phase: Choose mode ── */}
          {phase === 'choose' && (
            <div className="mode-selector">
              <h2>Editor SVG Overlay</h2>
              <p>Vyber režim práce</p>
              <div className="mode-cards">
                <div className="mode-card" onClick={() => setPhase('new')}>
                  <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
                    <rect x="4" y="4" width="40" height="40" rx="8" stroke="#3b82f6" strokeWidth="2" strokeDasharray="4 3"/>
                    <path d="M24 16v16M16 24h16" stroke="#3b82f6" strokeWidth="2.5" strokeLinecap="round"/>
                  </svg>
                  <h3>Nové SVG</h3>
                  <p>Nahraj podkladový obrázek a začni kreslit nový overlay</p>
                </div>
                <div className="mode-card" onClick={() => { setPhase('upload-edit'); setEditModeSvgLoaded(false); }}>
                  <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
                    <rect x="4" y="4" width="40" height="40" rx="8" stroke="#f59e0b" strokeWidth="2"/>
                    <path d="M16 28l6-8 4 5 4-3 6 6" stroke="#f59e0b" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                    <path d="M30 14l4 4-12 12H18v-4L30 14z" stroke="#f59e0b" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  <h3>Upravit existující</h3>
                  <p>Nahraj obrázek a vyexportované SVG pro úpravy</p>
                </div>
              </div>
            </div>
          )}

          {/* ── Phase: New — upload image ── */}
          {phase === 'new' && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16 }}>
              <div className="upload-zone" onClick={() => fileRef.current?.click()}
                onDragOver={e => { e.preventDefault(); }} onDrop={e => { e.preventDefault(); handleImageUpload(e.dataTransfer.files[0]); }}>
                <input ref={fileRef} type="file" accept="image/*" hidden onChange={e => handleImageUpload(e.target.files[0])} />
                <svg width="48" height="48" viewBox="0 0 48 48" fill="none" style={{ margin: '0 auto 16px' }}>
                  <rect x="4" y="4" width="40" height="40" rx="8" stroke="#3b82f6" strokeWidth="2" strokeDasharray="4 3"/>
                  <path d="M24 16v16M16 24h16" stroke="#3b82f6" strokeWidth="2" strokeLinecap="round"/>
                </svg>
                <h3>Nahraj podkladový obrázek</h3>
                <p>PNG, JPEG nebo jiný rastrový formát</p>
              </div>
              <button className="btn btn-sm" onClick={goBack}>← Zpět</button>
            </div>
          )}

          {/* ── Phase: Upload for edit ── */}
          {phase === 'upload-edit' && (
            <div className="edit-upload-step">
              <h3>Nahraj soubory pro úpravu</h3>
              <div className="edit-upload-row">
                <div className="upload-zone-mini" onClick={() => editImgRef.current?.click()}
                  onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); handleEditImageUpload(e.dataTransfer.files[0]); }}>
                  <input ref={editImgRef} type="file" accept="image/*" hidden onChange={e => handleEditImageUpload(e.target.files[0])} />
                  {image ? <><span className="badge badge-green">✓</span><p style={{ marginTop: 6 }}>Obrázek OK</p></> : <><h4>1. Obrázek</h4><p>PNG, JPEG…</p></>}
                </div>
                <div className="upload-zone-mini" onClick={() => editSvgRef.current?.click()}
                  onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); handleEditSvgUpload(e.dataTransfer.files[0]); }}>
                  <input ref={editSvgRef} type="file" accept=".svg" hidden onChange={e => handleEditSvgUpload(e.target.files[0])} />
                  {editModeSvgLoaded ? <><span className="badge badge-green">✓</span><p style={{ marginTop: 6 }}>{elements.length} prvků</p></> : <><h4>2. SVG</h4><p>.svg soubor</p></>}
                </div>
              </div>
              <div style={{ display: 'flex', gap: 12 }}>
                <button className="btn btn-sm" onClick={goBack}>← Zpět</button>
                <button className="btn btn-primary" disabled={!image || !editModeSvgLoaded} onClick={startEditCanvas}
                  style={{ opacity: (!image || !editModeSvgLoaded) ? 0.4 : 1 }}>Otevřít v editoru →</button>
              </div>
            </div>
          )}

          {/* ── Phase: Canvas ── */}
          {phase === 'canvas' && (
            <>
              <div style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`, transformOrigin: '0 0' }}>
                <div className="canvas-wrapper">
                  <img ref={imgRef} src={image} alt="Base" draggable={false} style={{ maxWidth: '70vw', maxHeight: '75vh' }} />
                  <svg ref={svgRef} className={editGeomId ? '' : 'drawing-svg'}
                    viewBox={`0 0 ${imgSize.w} ${imgSize.h}`}
                    onClick={handleCanvasClick} onDoubleClick={handleDoubleClick}
                    style={editGeomId ? { cursor: 'default' } : {}}>

                    {/* Saved polygons */}
                    {elements.map(el => {
                      const isSelected = selectedId === el.id;
                      const isGeomEdit = editGeomId === el.id;
                      let fill = 'var(--polygon-fill)';
                      let stroke = 'var(--polygon-stroke)';
                      if (isGeomEdit) { fill = 'rgba(249,115,22,0.15)'; stroke = 'var(--vertex-edit)'; }
                      else if (isSelected) { fill = 'var(--polygon-selected-fill)'; stroke = 'var(--polygon-selected-stroke)'; }
                      return (
                        <polygon key={el.id}
                          points={el.points.map(p => `${p.x},${p.y}`).join(' ')}
                          fill={fill} stroke={stroke}
                          strokeWidth={isGeomEdit ? strokeW * 1.5 : strokeW}
                          strokeLinejoin="round"
                          onClick={(e) => handlePolygonClick(e, el.id)} />
                      );
                    })}

                    {/* Geometry edit: vertex handles */}
                    {editGeomEl && editGeomEl.points.map((p, i) => (
                      <g key={`v-${i}`}>
                        {/* Draggable vertex */}
                        <circle cx={p.x} cy={p.y} r={vertexR}
                          fill="var(--vertex-edit)" stroke="var(--bg-primary)" strokeWidth={strokeW * 0.5}
                          style={{ cursor: 'move' }}
                          onMouseDown={(e) => handleVertexMouseDown(e, editGeomEl.id, i)} />
                        {/* Right-click to delete vertex */}
                        <circle cx={p.x} cy={p.y} r={vertexR * 1.8}
                          fill="transparent" stroke="none"
                          style={{ cursor: 'move' }}
                          onMouseDown={(e) => handleVertexMouseDown(e, editGeomEl.id, i)}
                          onContextMenu={(e) => { e.preventDefault(); e.stopPropagation(); removeVertex(editGeomEl.id, i); }} />
                        {/* Midpoint for adding vertex */}
                        {(() => {
                          const next = editGeomEl.points[(i + 1) % editGeomEl.points.length];
                          const mx = (p.x + next.x) / 2, my = (p.y + next.y) / 2;
                          return (
                            <circle cx={mx} cy={my} r={midpointR}
                              fill="var(--bg-tertiary)" stroke="var(--vertex-edit)" strokeWidth={strokeW * 0.4}
                              opacity="0.6" style={{ cursor: 'pointer' }}
                              onClick={(e) => { e.stopPropagation(); addVertex(editGeomEl.id, i); }} />
                          );
                        })()}
                      </g>
                    ))}

                    {/* Drawing: polyline + dots */}
                    {currentPoints.length >= 2 && (
                      <polyline points={currentPoints.map(p => `${p.x},${p.y}`).join(' ')}
                        fill="none" stroke="var(--polygon-active-stroke)" strokeWidth={strokeW}
                        strokeDasharray={`${strokeW * 3} ${strokeW * 2}`} strokeLinejoin="round" />
                    )}
                    {currentPoints.length >= 3 && (
                      <line x1={currentPoints[currentPoints.length - 1].x} y1={currentPoints[currentPoints.length - 1].y}
                        x2={currentPoints[0].x} y2={currentPoints[0].y}
                        stroke="var(--success)" strokeWidth={strokeW * 0.8}
                        strokeDasharray={`${strokeW * 2} ${strokeW * 2}`} opacity="0.6" />
                    )}
                    {currentPoints.map((p, i) => {
                      const isFirst = i === 0 && currentPoints.length >= 3;
                      return (
                        <g key={`dp-${i}`}>
                          {isFirst && <circle cx={p.x} cy={p.y} r={closeDotRadius * 2.5} fill="transparent" stroke="none" style={{ cursor: 'pointer' }} />}
                          <circle cx={p.x} cy={p.y} r={isFirst ? closeDotRadius : dotRadius}
                            fill={isFirst ? 'var(--success)' : 'var(--polygon-active-stroke)'}
                            stroke="var(--bg-primary)" strokeWidth={strokeW * 0.6}
                            style={isFirst ? { cursor: 'pointer', filter: `drop-shadow(0 0 ${8/zoom}px rgba(16,185,129,0.7))` } : {}} />
                          {isFirst && (
                            <circle cx={p.x} cy={p.y} r={closeDotRadius * 1.8}
                              fill="none" stroke="var(--success)" strokeWidth={strokeW * 0.4} opacity="0.4">
                              <animate attributeName="r" from={closeDotRadius * 1.4} to={closeDotRadius * 2.5} dur="1.5s" repeatCount="indefinite" />
                              <animate attributeName="opacity" from="0.5" to="0" dur="1.5s" repeatCount="indefinite" />
                            </circle>
                          )}
                        </g>
                      );
                    })}
                  </svg>
                </div>
              </div>
              <div className="zoom-controls">
                <button className="zoom-btn" onClick={zoomOut}>−</button>
                <div className="zoom-info">{Math.round(zoom * 100)}%</div>
                <button className="zoom-btn" onClick={zoomIn}>+</button>
                <button className="zoom-btn" onClick={() => { const ds = getDisplayedImgSize(); resetView(ds.w, ds.h); }}>⌂</button>
              </div>
            </>
          )}
        </div>

        {/* ── SIDEBAR ── */}
        <div className="sidebar">
          <div className="sidebar-tabs">
            <button className={`sidebar-tab ${sidebarTab === 'elements' ? 'active' : ''}`} onClick={() => setSidebarTab('elements')}>
              Prvky {elements.length > 0 && <span className="badge badge-blue" style={{ marginLeft: 6 }}>{elements.length}</span>}
            </button>
            <button className={`sidebar-tab ${sidebarTab === 'groups' ? 'active' : ''}`} onClick={() => setSidebarTab('groups')}>
              Skupiny {groups.length > 0 && <span className="badge badge-purple" style={{ marginLeft: 6 }}>{groups.length}</span>}
            </button>
          </div>
          <div className="sidebar-content">
            {sidebarTab === 'elements' ? (
              editId ? (
                /* ── Attribute editor ── */
                <div style={{ animation: 'fadeIn 0.2s ease' }}>
                  <GroupSwitcher groups={groups} activeGroupId={activeGroupId} setActiveGroupId={setActiveGroupId} />
                  <div className="form-group">
                    <label className="form-label">ID prvku</label>
                    <input className="form-input" value={editElId} onChange={e => setEditElId(e.target.value)} placeholder="unikátní identifikátor" />
                  </div>
                  <div className="divider" />
                  <label className="form-label" style={{ marginBottom: 10 }}>Atributy</label>
                  {editAttrs.map((attr, i) => (
                    <div key={i} className="attr-row">
                      <input className="form-input" placeholder="klíč" value={attr.key}
                        onChange={e => { const n = [...editAttrs]; n[i] = { ...n[i], key: e.target.value }; setEditAttrs(n); }} />
                      <input className="form-input" placeholder="hodnota" value={attr.value}
                        onChange={e => { const n = [...editAttrs]; n[i] = { ...n[i], value: e.target.value }; setEditAttrs(n); }} />
                      <button className="remove-attr" onClick={() => { if (editAttrs.length > 1) setEditAttrs(editAttrs.filter((_, j) => j !== i)); }}>×</button>
                    </div>
                  ))}
                  <button className="btn btn-sm" style={{ marginTop: 4, width: '100%', justifyContent: 'center' }}
                    onClick={() => setEditAttrs([...editAttrs, { key: '', value: '' }])}>+ Přidat atribut</button>
                  <div className="divider" />
                  <div style={{ display: 'flex', gap: 8 }}>
                    <button className="btn btn-primary" style={{ flex: 1, justifyContent: 'center' }} onClick={saveAttributes}>Uložit</button>
                    <button className="btn" style={{ flex: 1, justifyContent: 'center' }} onClick={() => { setEditId(null); }}>Zrušit</button>
                  </div>
                </div>
              ) : editGeomId ? (
                /* ── Geometry edit panel ── */
                <div style={{ animation: 'fadeIn 0.2s ease' }}>
                  <div className="geom-hint">
                    <strong>Úprava geometrie:</strong> {editGeomEl?.id}<br/>
                    Přetahuj <strong>oranžové body</strong> pro přesun.<br/>
                    Klikni na <strong>malé body na hranách</strong> pro přidání bodu.<br/>
                    <strong>Pravý klik</strong> na bod pro odebrání (min. 3).<br/>
                    <strong>Esc</strong> pro ukončení.
                  </div>
                  {editGeomEl && (
                    <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 12 }}>
                      {editGeomEl.points.length} bodů
                    </div>
                  )}
                  <button className="btn" style={{ width: '100%', justifyContent: 'center' }} onClick={stopGeomEdit}>
                    ✓ Hotovo
                  </button>
                </div>
              ) : (
                /* ── Element list ── */
                <>
                  <GroupSwitcher groups={groups} activeGroupId={activeGroupId} setActiveGroupId={setActiveGroupId} />
                  {phase !== 'canvas' && <div className="hint-box">Vyber režim editoru a nahraj soubory.</div>}
                  {phase === 'canvas' && elements.length === 0 && (
                    <div className="hint-box">
                      <strong>Jak kreslit:</strong><br />
                      Klikej na plátno pro body polygonu.<br />
                      Klikni na <span style={{ color: 'var(--success)' }}>zelený bod</span> nebo dvojklik pro uzavření.<br />
                      <span style={{ color: 'var(--text-muted)' }}>Kolečko</span> = zoom, <span style={{ color: 'var(--text-muted)' }}>Ctrl+tah</span> = posun<br />
                      <span style={{ color: 'var(--text-muted)' }}>F2</span> = přejmenovat, <span style={{ color: 'var(--text-muted)' }}>Del</span> = smazat
                    </div>
                  )}
                  {elements.map(el => (
                    <div key={el.id}
                      className={`element-item ${selectedId === el.id ? 'selected' : ''}`}
                      onClick={() => setSelectedId(el.id)}>
                      <div className="el-info">
                        {renamingId === el.id ? (
                          <input ref={renameInputRef} className="inline-rename" value={renameValue}
                            onChange={e => setRenameValue(e.target.value)}
                            onBlur={commitRename}
                            onKeyDown={e => { if (e.key === 'Enter') commitRename(); if (e.key === 'Escape') cancelRename(); }}
                            onClick={e => e.stopPropagation()} autoFocus />
                        ) : (
                          <div className="el-id" onDoubleClick={(e) => { e.stopPropagation(); startRename(el.id); }}>
                            {el.id}
                          </div>
                        )}
                        <div className="el-points">
                          {el.points.length} bodů · {el.attributes.length} attr
                          {el.groupName && <span className="badge badge-purple" style={{ marginLeft: 4 }}>{el.groupName}</span>}
                        </div>
                      </div>
                      <div className="el-actions">
                        <button className="btn btn-xs btn-orange" title="Upravit geometrii"
                          onClick={(e) => { e.stopPropagation(); startGeomEdit(el.id); }}>⬡</button>
                        <button className="btn btn-xs" title="Upravit atributy"
                          onClick={(e) => { e.stopPropagation(); startEditAttrs(el.id); }}>✎</button>
                        <button className="btn btn-xs btn-danger" title="Smazat"
                          onClick={(e) => { e.stopPropagation(); deleteElement(el.id); }}>×</button>
                      </div>
                    </div>
                  ))}
                </>
              )
            ) : (
              /* ═══ GROUPS TAB ═══ */
              editingGroup ? (
                <div style={{ animation: 'fadeIn 0.2s ease' }}>
                  <div className="form-group">
                    <label className="form-label">Název skupiny</label>
                    <input className="form-input" value={groupForm.name}
                      onChange={e => setGroupForm({ ...groupForm, name: e.target.value })}
                      placeholder="např. Budova, Park, Silnice…" />
                  </div>
                  <div className="divider" />
                  <label className="form-label" style={{ marginBottom: 10 }}>Názvy atributů (klíče)</label>
                  {groupForm.attrKeys.map((key, i) => (
                    <div key={i} className="attr-row">
                      <input className="form-input" placeholder="název atributu" value={key}
                        onChange={e => { const n = [...groupForm.attrKeys]; n[i] = e.target.value; setGroupForm({ ...groupForm, attrKeys: n }); }} />
                      <button className="remove-attr" onClick={() => {
                        if (groupForm.attrKeys.length > 1) setGroupForm({ ...groupForm, attrKeys: groupForm.attrKeys.filter((_, j) => j !== i) });
                      }}>×</button>
                    </div>
                  ))}
                  <button className="btn btn-sm" style={{ marginTop: 4, width: '100%', justifyContent: 'center' }}
                    onClick={() => setGroupForm({ ...groupForm, attrKeys: [...groupForm.attrKeys, ''] })}>+ Přidat atribut</button>
                  <div className="divider" />
                  <div style={{ display: 'flex', gap: 8 }}>
                    <button className="btn btn-purple" style={{ flex: 1, justifyContent: 'center' }} onClick={saveGroup}>Uložit skupinu</button>
                    <button className="btn" style={{ flex: 1, justifyContent: 'center' }} onClick={() => setEditingGroup(null)}>Zrušit</button>
                  </div>
                </div>
              ) : (
                <>
                  <div className="hint-box" style={{ marginBottom: 16 }}>
                    Skupiny definují <strong>šablony atributů</strong>. Vytvoř skupinu, aktivuj ji přes rozbalovací menu v záložce Prvky.
                  </div>
                  <button className="btn btn-purple" style={{ width: '100%', justifyContent: 'center', marginBottom: 16 }}
                    onClick={startNewGroup}>+ Nová skupina</button>
                  {groups.map(g => (
                    <div key={g.id} className={`group-card ${activeGroupId === g.id ? 'active-group' : ''}`}>
                      <div className="group-name">
                        <span>{g.name}</span>
                        {activeGroupId === g.id && <span className="badge badge-purple">aktivní</span>}
                      </div>
                      <div className="group-attrs">Atributy: {g.attrKeys.join(', ')}</div>
                      <div className="group-actions">
                        <button className="btn btn-sm" onClick={() => startEditGroup(g)}>Upravit</button>
                        <button className="btn btn-sm btn-danger" onClick={() => deleteGroup(g.id)}>Smazat</button>
                      </div>
                    </div>
                  ))}
                </>
              )
            )}
          </div>

          {/* ── Fixed action bar (always visible) ── */}
          {phase === 'canvas' && elements.length > 0 && !editId && !editGeomId && sidebarTab === 'elements' && (
            <div className="sidebar-actions">
              <button className="btn btn-primary btn-sm" onClick={exportSVG}>↓ Exportovat SVG</button>
              <button className="btn btn-sm" onClick={exportLibrary}>↓ JS knihovna</button>
              <button className="btn btn-sm" style={{ fontSize: 10, color: 'var(--text-muted)' }} onClick={goBack}>← Nový projekt</button>
            </div>
          )}
        </div>
      </div>

      <div className="statusbar">
        <span><span className={`status-dot ${phase === 'canvas' ? 'green' : 'yellow'}`} />
          {phase === 'canvas' ? 'Editor' : phase === 'choose' ? 'Výběr režimu' : 'Nahrávání'}</span>
        {imgSize.w > 0 && <span>{imgSize.w}×{imgSize.h}</span>}
        <span>{elements.length} prvků</span>
        {isDrawing && <span><span className="status-dot blue" />Kreslení · {currentPoints.length} bodů</span>}
        {editGeomId && <span><span className="status-dot orange" />Úprava geometrie</span>}
        {activeGroup && <span style={{ color: 'var(--group-purple)' }}>⬡ {activeGroup.name}</span>}
        {zoom !== 1 && <span>{Math.round(zoom * 100)}%</span>}
      </div>
    </>
  );
}

// ═══════════════════════════════════════════
// ─── VALIDATOR ───
// ═══════════════════════════════════════════
function Validator() {
  const [image, setImage] = useState(null);
  const [svgContent, setSvgContent] = useState(null);
  const [svgElements, setSvgElements] = useState([]);
  const [selectedEl, setSelectedEl] = useState(null);
  const [imgSize, setImgSize] = useState({ w: 0, h: 0 });
  const fileRefImg = useRef(null);
  const fileRefSvg = useRef(null);
  const wrapperRef = useRef(null);
  const canvasAreaRef = useRef(null);
  const { zoom, pan, resetView, centerOn, zoomIn, zoomOut, isPanning } = useZoomPan(canvasAreaRef, !image || !svgContent);

  const getDisplayedImgSize = useCallback(() => {
    if (!imgSize.w || !imgSize.h) return { w: 0, h: 0 };
    const maxW = window.innerWidth * 0.7;
    const maxH = window.innerHeight * 0.75;
    const scale = Math.min(maxW / imgSize.w, maxH / imgSize.h, 1);
    return { w: imgSize.w * scale, h: imgSize.h * scale };
  }, [imgSize]);

  // Auto-center when both files loaded
  const bothLoaded = !!(image && svgContent);
  const prevBothLoaded = useRef(false);
  useEffect(() => {
    if (bothLoaded && !prevBothLoaded.current) {
      const ds = getDisplayedImgSize();
      requestAnimationFrame(() => centerOn(ds.w, ds.h));
    }
    prevBothLoaded.current = bothLoaded;
  }, [bothLoaded, centerOn, getDisplayedImgSize]);

  const handleImageUpload = (file) => {
    if (!file) return;
    const url = URL.createObjectURL(file);
    const img = new Image();
    img.onload = () => { setImgSize({ w: img.naturalWidth, h: img.naturalHeight }); setImage(url); };
    img.src = url;
  };
  const handleSVGUpload = (file) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (e) => {
      const text = e.target.result; setSvgContent(text);
      const parser = new DOMParser();
      const doc = parser.parseFromString(text, 'image/svg+xml');
      const polys = doc.querySelectorAll('[data-overlay-id]');
      const els = Array.from(polys).map(p => {
        const attrs = {};
        Array.from(p.attributes).forEach(a => { if (a.name.startsWith('data-') && a.name !== 'data-overlay-id') attrs[a.name.replace('data-', '')] = a.value; });
        return { id: p.getAttribute('data-overlay-id'), points: p.getAttribute('points'), tag: p.tagName, attrs };
      });
      setSvgElements(els); setSelectedEl(null);
    };
    reader.readAsText(file);
  };
  const handleOverlayClick = (e) => {
    if (['polygon', 'rect', 'circle'].includes(e.target.tagName)) {
      const id = e.target.getAttribute('data-overlay-id');
      if (id) { setSelectedEl(svgElements.find(x => x.id === id) || null); return; }
    }
    setSelectedEl(null);
  };

  useEffect(() => {
    if (!wrapperRef.current || !svgContent) return;
    const container = wrapperRef.current.querySelector('.validator-svg-container');
    if (!container) return;
    container.innerHTML = svgContent;
    const svg = container.querySelector('svg');
    if (svg) {
      svg.style.cssText = 'position:absolute;top:0;left:0;width:100%;height:100%;cursor:pointer;';
      svg.querySelectorAll('[data-overlay-id]').forEach(el => {
        el.style.cursor = 'pointer'; el.style.pointerEvents = 'all'; el.style.transition = 'fill 0.15s';
        el.addEventListener('mouseenter', () => el.setAttribute('fill', 'rgba(250,204,21,0.35)'));
        el.addEventListener('mouseleave', () => {
          const isSel = selectedEl && selectedEl.id === el.getAttribute('data-overlay-id');
          el.setAttribute('fill', isSel ? 'rgba(250,204,21,0.35)' : 'rgba(59,130,246,0.25)');
        });
      });
    }
  }, [svgContent, selectedEl]);

  return (
    <>
      <div className="workspace">
        <div className="canvas-area" ref={canvasAreaRef}
          style={(image && svgContent) ? { alignItems: 'flex-start', justifyContent: 'flex-start' } : {}}>
          {(!image || !svgContent) ? (
            <div style={{ display: 'flex', gap: 24, alignItems: 'start' }}>
              <div className="upload-zone" onClick={() => fileRefImg.current?.click()}
                onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); handleImageUpload(e.dataTransfer.files[0]); }}>
                <input ref={fileRefImg} type="file" accept="image/*" hidden onChange={e => handleImageUpload(e.target.files[0])} />
                {image ? <><span className="badge badge-green">✓</span><p style={{ marginTop: 8 }}>OK</p></> : <><h3>1. Obrázek</h3><p>PNG, JPEG…</p></>}
              </div>
              <div className="upload-zone" onClick={() => fileRefSvg.current?.click()}
                onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); handleSVGUpload(e.dataTransfer.files[0]); }}>
                <input ref={fileRefSvg} type="file" accept=".svg" hidden onChange={e => handleSVGUpload(e.target.files[0])} />
                {svgContent ? <><span className="badge badge-green">✓</span><p style={{ marginTop: 8 }}>{svgElements.length} prvků</p></> : <><h3>2. SVG</h3><p>.svg soubor</p></>}
              </div>
            </div>
          ) : (
            <>
              <div style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`, transformOrigin: '0 0' }}>
                <div className="canvas-wrapper" ref={wrapperRef} onClick={handleOverlayClick}>
                  <img src={image} alt="Base" draggable={false} style={{ display: 'block', maxWidth: '70vw', maxHeight: '75vh' }} />
                  <div className="validator-svg-container" />
                </div>
              </div>
              <div className="zoom-controls">
                <button className="zoom-btn" onClick={zoomOut}>−</button>
                <div className="zoom-info">{Math.round(zoom * 100)}%</div>
                <button className="zoom-btn" onClick={zoomIn}>+</button>
                <button className="zoom-btn" onClick={() => { const ds = getDisplayedImgSize(); resetView(ds.w, ds.h); }}>⌂</button>
              </div>
            </>
          )}
        </div>
        <div className="sidebar">
          <div className="sidebar-tabs"><button className="sidebar-tab active">Validátor</button></div>
          <div className="sidebar-content">
            {!image || !svgContent ? (
              <div className="hint-box">Nahraj obrázek a SVG pro validaci.</div>
            ) : selectedEl ? (
              <div style={{ animation: 'fadeIn 0.2s ease' }}>
                <div className="form-group">
                  <label className="form-label">ID</label>
                  <div className="form-input" style={{ background: 'var(--bg-tertiary)' }}>{selectedEl.id}</div>
                </div>
                <div className="form-group">
                  <label className="form-label">Geometrie</label>
                  <div className="form-input" style={{ background: 'var(--bg-tertiary)', fontSize: 11, wordBreak: 'break-all', lineHeight: 1.5 }}>{selectedEl.points}</div>
                </div>
                {Object.keys(selectedEl.attrs).length > 0 && (
                  <><div className="divider" /><label className="form-label">Atributy</label>
                    <table className="validator-attrs-table"><tbody>
                      {Object.entries(selectedEl.attrs).map(([k, v]) => (<tr key={k}><td>{k}</td><td>{v}</td></tr>))}
                    </tbody></table></>
                )}
              </div>
            ) : (
              <>
                <div className="hint-box" style={{ marginBottom: 16 }}>Klikni na prvek v mapě.</div>
                <label className="form-label">Prvky ({svgElements.length})</label>
                {svgElements.map(el => (
                  <div key={el.id} className="element-item" onClick={() => setSelectedEl(el)}>
                    <div className="el-info"><div className="el-id">{el.id}</div><div className="el-points">{Object.keys(el.attrs).length} attr</div></div>
                    <span className="badge badge-blue">{el.tag}</span>
                  </div>
                ))}
              </>
            )}
          </div>
        </div>
      </div>
      <div className="statusbar">
        <span><span className={`status-dot ${image && svgContent ? 'green' : 'yellow'}`} />{image && svgContent ? 'Validace' : 'Čeká na soubory'}</span>
        {svgElements.length > 0 && <span>{svgElements.length} prvků</span>}
        {selectedEl && <span>Vybrán: {selectedEl.id}</span>}
        {zoom !== 1 && <span>{Math.round(zoom * 100)}%</span>}
      </div>
    </>
  );
}
